apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fulfillhub-runtime
  namespace: fulfillhub
  labels:
    app.kubernetes.io/name: fulfillhub
    app.kubernetes.io/part-of: fulfillhub-commerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: production-secret-store
    kind: ClusterSecretStore
  target:
    name: fulfillhub-runtime
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fulfillhub/prod/database-url
    - secretKey: RABBITMQ_URL
      remoteRef:
        key: fulfillhub/prod/rabbitmq-url
    - secretKey: REDIS_URL
      remoteRef:
        key: fulfillhub/prod/redis-url
    - secretKey: OPS_JWT_SECRET
      remoteRef:
        key: fulfillhub/prod/ops-jwt-secret
    - secretKey: OPS_JWT_PREVIOUS_SECRETS
      remoteRef:
        key: fulfillhub/prod/ops-jwt-previous-secrets
    - secretKey: METRICS_BEARER_TOKEN
      remoteRef:
        key: fulfillhub/prod/metrics-bearer-token
    - secretKey: PAYMENT_WEBHOOK_SECRET
      remoteRef:
        key: fulfillhub/prod/payment-webhook-secret
    - secretKey: SHIPMENT_WEBHOOK_SECRET
      remoteRef:
        key: fulfillhub/prod/shipment-webhook-secret
