apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fulfillhub-api
  namespace: fulfillhub
  labels:
    app.kubernetes.io/name: fulfillhub-api
    app.kubernetes.io/part-of: fulfillhub-commerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fulfillhub-api
  minReplicas: 3
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
