apiVersion: v1
kind: ServiceAccount
metadata:
  name: fulfillhub-runtime
  namespace: fulfillhub
  labels:
    app.kubernetes.io/name: fulfillhub
    app.kubernetes.io/part-of: fulfillhub-commerce
automountServiceAccountToken: false
